name: Deploy to production server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ============ 🎨 Frontend ===============
            ♻️ Сейчас будут выкачены новые изменения

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Node install
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with Pnpm
        run: pnpm install

      - name: Compile TypeScript
        run: pnpm build

      - name: Create BZIP deployment package
        run: tar -cjf build-front.tar.bz2 dist/*

      - name: Copy file to serve
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: build-front.tar.bz2
          target: ~/uploads/

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/renderlife/frontend/
            rm -rf *
            tar -C ./ -xjf ~/uploads/build-front.tar.bz2 --strip-components 1
            rm -rf ~/uploads/build-front.tar.bz2

      - name: Success Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            🎉 Деплой приложения «jQuery Todo - 🎨 Frontend
            на сервер Мечты успешно завершен.
            Название коммита: ${{ github.event.commits[0].message }}

      - name: Failed Notification
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            🔥 Деплой приложения «jQuery Todo - 🎨 Frontend
            на сервер Мечты завершен неудачей.
            Название коммита: ${{ github.event.commits[0].message }}

